config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root 'properties#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    validates :property, :rent, :address, :building_age, :remarks, presence: true
    validate :check
    def check
        if how_many_minutes_walk.present? && how_many_minute_walk.present?
            if how_many_minutes_walk <= how_many_minute_walk
                errors.add(:how_many_minutes_walk, 'not perfect')
            end
        end
    
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property, :rent, :address, :building_age, :remarks, :name_of_railway_line, :station_name, :how_many_minutes_walk, :name_of_rail_way_line, :stationname, :how_many_minute_walk)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property %>
    <%= f.text_field :property %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.number_field :rent %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :building_age %>
    <%= f.number_field :building_age %>
  </div>

  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_area :remarks %>
  </div>
 <h2>Name of railway line 1</h2>
  <div class="field">
    <%= f.label :name_of_railway_line %>
    <%= f.text_field :name_of_railway_line %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>

  <div class="field">
    <%= f.label :how_many_minutes_walk %>
    <%= f.number_field :how_many_minutes_walk %>
  </div>
  <h2>Name of railway line 2</h2>
  <div class="field">
    <%= f.label :name_of_railway_line %>
    <%= f.text_field :name_of_rail_way_line %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :stationname %>
  </div>

  <div class="field">
    <%= f.label :how_many_minutes_walk %>
    <%= f.number_field :how_many_minute_walk %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Remarks</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
       
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building_age %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>

<p>
  <strong>Name of railway line:</strong>
  <%= @property.name_of_railway_line %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @property.station_name %>
</p>

<p>
  <strong>How many minutes walk:</strong>
  <%= @property.how_many_minutes_walk %>
</p>

<p>
  <strong>Name of railway line:</strong>
  <%= @property.name_of_rail_way_line %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @property.stationname %>
</p>

<p>
  <strong>How many minutes walk:</strong>
  <%= @property.how_many_minute_walk %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>